services:
  - type: web
    name: foodeo-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RAZORPAY_KEY_ID
        value: rzp_test_Rn2y1nsEX5U59v
      - key: RAZORPAY_KEY_SECRET
        value: 7tfrzU63nQPRPavKu1IFtxyn
      - key: SUPABASE_URL
        value: https://msytkjavapigijxqreji.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeXRramF2YXBpZ2lqeHFyZWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMTcyODUsImV4cCI6MjA3OTc5MzI4NX0.a0RkoCttEO5TFVuND6VhkdYzHeP835sGcY-dALXKpbM
      - key: CORS_ORIGINS
        value: https://foodeo-liard.vercel.app
